steps:
  - name: 'gcr.io/cloud-builders/git'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        echo "Analyzing changed files..."
        git diff --name-only HEAD~1 HEAD > /workspace/changed_files.txt || echo "No previous commit, building all"
        if [ ! -s /workspace/changed_files.txt ]; then
          echo "src/" > /workspace/changed_files.txt
          echo "tts_api/" >> /workspace/changed_files.txt
        fi
        echo "Changed files:"
        cat /workspace/changed_files.txt

  - name: 'ubuntu'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        if grep -E '^(src/|Dockerfile|package\.json|next\.config|tailwind|postcss)' /workspace/changed_files.txt; then
          echo "NextJS app files changed - building app"
          echo "BUILD_NEXTJS=true" >> /workspace/build_flags.txt
        else
          echo "NextJS app unchanged - skipping"
          echo "BUILD_NEXTJS=false" >> /workspace/build_flags.txt
        fi

  - name: 'ubuntu'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        if grep -E '^tts_api/' /workspace/changed_files.txt; then
          echo "TTS API files changed - building API"
          echo "BUILD_TTS=true" >> /workspace/build_flags.txt
        else
          echo "TTS API unchanged - skipping"
          echo "BUILD_TTS=false" >> /workspace/build_flags.txt
        fi

  - name: 'gcr.io/cloud-builders/docker'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        if grep "BUILD_NEXTJS=true" /workspace/build_flags.txt; then
          echo "Building NextJS Docker image..."
          docker build -t ${_NEXTJS_IMAGE_URL}:latest -t ${_NEXTJS_IMAGE_URL}:${BUILD_ID} .
        else
          echo "Skipping NextJS build"
        fi

  - name: 'gcr.io/cloud-builders/docker'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        if grep "BUILD_TTS=true" /workspace/build_flags.txt; then
          echo "Building TTS Docker image..."
          docker build -f tts_api/Dockerfile -t ${_TTS_IMAGE_URL}:latest -t ${_TTS_IMAGE_URL}:${BUILD_ID} ./tts_api
        else
          echo "Skipping TTS build"
        fi

  - name: 'gcr.io/cloud-builders/docker'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        if grep "BUILD_NEXTJS=true" /workspace/build_flags.txt; then
          echo "Pushing NextJS images..."
          docker push ${_NEXTJS_IMAGE_URL}:latest
          docker push ${_NEXTJS_IMAGE_URL}:${BUILD_ID}
        else
          echo "Skipping NextJS push"
        fi

  - name: 'gcr.io/cloud-builders/docker'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        if grep "BUILD_TTS=true" /workspace/build_flags.txt; then
          echo "Pushing TTS images..."
          docker push ${_TTS_IMAGE_URL}:latest
          docker push ${_TTS_IMAGE_URL}:${BUILD_ID}
        else
          echo "Skipping TTS push"
        fi

  - name: 'gcr.io/cloud-builders/gcloud'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        if grep "BUILD_NEXTJS=true" /workspace/build_flags.txt; then
          echo "Deploying NextJS app..."
          gcloud run deploy voicecast-app \
            --image ${_NEXTJS_IMAGE_URL}:latest \
            --region ${_REGION} \
            --platform managed \
            --quiet
        else
          echo "Skipping NextJS deployment"
        fi

  - name: 'gcr.io/cloud-builders/gcloud'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        if grep "BUILD_TTS=true" /workspace/build_flags.txt; then
          echo "Deploying TTS API..."
          gcloud run deploy voicecast-tts \
            --image ${_TTS_IMAGE_URL}:latest \
            --region ${_REGION} \
            --platform managed \
            --quiet
        else
          echo "Skipping TTS deployment"
        fi

  - name: 'gcr.io/cloud-builders/gcloud'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        echo "Deployment completed!"
        echo "Build flags:"
        cat /workspace/build_flags.txt
        echo "Services deployed based on changed files."

options:
  machineType: 'E2_HIGHCPU_8'
  diskSizeGb: 100
  logging: 'CLOUD_LOGGING_ONLY'

timeout: '1800s'

substitutions:
  _NEXTJS_IMAGE_URL: 'europe-west1-docker.pkg.dev/voicecast-464815/voicecast/voicecast-app'
  _TTS_IMAGE_URL: 'europe-west1-docker.pkg.dev/voicecast-464815/voicecast/voicecast-tts'
  _REGION: 'europe-west1'

tags:
  - 'voicecast'
  - 'smart-deploy'
  - 'path-based-builds'