steps:
  - name: 'gcr.io/cloud-builders/gcloud'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        echo "Starting VoiceCast app deployment"
        echo "Build ID: $BUILD_ID"
        echo "Branch: $BRANCH_NAME"
        echo "Commit: $COMMIT_SHA"
        echo "Triggered by: App file changes (fast deployment)"

  - name: 'gcr.io/cloud-builders/docker'
    args: [
      'build',
      '-t', '${_IMAGE_URL}:latest',
      '-t', '${_IMAGE_URL}:${BUILD_ID}',
      '.'
    ]

  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', '${_IMAGE_URL}:latest']

  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', '${_IMAGE_URL}:${BUILD_ID}']

  - name: 'gcr.io/cloud-builders/gcloud'
    args: [
      'run', 'deploy', 'voicecast-app',
      '--image', '${_IMAGE_URL}:latest',
      '--region', '${_REGION}',
      '--platform', 'managed',
      '--quiet'
    ]

  - name: 'gcr.io/cloud-builders/gcloud'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        echo "VoiceCast app deployment completed successfully!"
        echo "Image: ${_IMAGE_URL}:latest"

options:
  machineType: 'E2_HIGHCPU_8'

  diskSizeGb: 50

  logging: 'CLOUD_LOGGING_ONLY'

timeout: '600s'

substitutions:
  _IMAGE_URL: 'europe-west9-docker.pkg.dev/voicecast-464815/voicecast/voicecast-app'
  _REGION: 'europe-west9'

tags:
  - 'voicecast'
  - 'nextjs'
  - 'app-deployment'
  - 'fast-deploy'