steps:
  - name: 'gcr.io/cloud-builders/docker'
    args: [
      'build',
      '-t', '${_NEXTJS_IMAGE_URL}:latest',
      '-t', '${_NEXTJS_IMAGE_URL}:${BUILD_ID}',
      '.'
    ]

  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', '${_NEXTJS_IMAGE_URL}:latest']

  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', '${_NEXTJS_IMAGE_URL}:${BUILD_ID}']

  - name: 'gcr.io/cloud-builders/gcloud'
    args: [
      'run', 'deploy', 'voicecast-app',
      '--image', '${_NEXTJS_IMAGE_URL}:latest',
      '--region', '${_REGION}',
      '--platform', 'managed',
      '--quiet'
    ]

options:
  machineType: 'E2_HIGHCPU_8'
  diskSizeGb: 100
  logging: 'CLOUD_LOGGING_ONLY'

timeout: '1200s'

substitutions:
  _NEXTJS_IMAGE_URL: 'europe-west1-docker.pkg.dev/voicecast-464815/voicecast/voicecast-app'
  _REGION: 'europe-west1'

tags:
  - 'voicecast'
  - 'app'
  - 'frontend'